export const formattedColumns = {
  cod_pes: "Código de pessoa",
  nome: "Nome",
  razao: "Razão social",
  logradouro: "Logradouro",
  numero: "Número",
  bairro: "Bairro",
  cidade: "Cidade",
  cep: "CEP",
  uf: "UF",
  ie: "Inscrição Estadual",
  contato: "Contato",
  sistema: "Sistema",
  serial: "Serial",
  obs: "Observações",
  ven_cert: "Vencimento do certificado",
  email: "Email",
  cnpj: "CNPJ",
  situacao: "Situação",
  tef: "TEF",
  nfe: "NFE",
  sped: "SPED",
  contador: "Contador",
  email_backup: "Email de backup",
  senha_backup: "Senha de backup",
  telefone: "Telefone",
  status: "Status",
};
