export type Person = {
  cod_pes?: string;
  nome?: string;
  razao?: string;
  logradouro?: string;
  numero?: string;
  bairro?: string;
  cidade?: string;
  cep?: string;
  uf?: string;
  ie?: string;
  contato?: string;
  sistema?: string;
  serial?: string;
  obs?: string;
  ven_cert?: string;
  email?: string;
  situacao?: string;
  tef?: string;
  nfe?: string;
  sped?: string;
  contador?: string;
  email_backup?: string;
  senha_backup?: string;
  tipo?: "contador" | "cliente";
};

export type PersonFormData = {
  nome: string;
  senha?: string;
  razao?: string;
  logradouro?: string;
  numero?: string;
  bairro?: string;
  cidade?: string;
  cep?: string;
  uf?: string;
  ie?: string;
  contato?: string;
  sistema: string;
  serial?: string;
  obs?: string;
  ven_cert?: string;
  email?: string;
  situacao?: string;
  tef?: string;
  nfe?: string;
  sped?: string;
  contador?: string;
  email_backup?: string;
  senha_backup?: string;
  tipo: "contador" | "cliente";
};
